name: .NET

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: MonitorWebAPI
    - name: Build
      run: dotnet build --no-restore
      working-directory: MonitorWebAPI
    - name: Unit Testing
      run: dotnet test
      working-directory: MonitorWebAPI
  
  deploy:
    
    needs: build
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Main Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            deployMainServer
